// Package bundle defines signed, product-neutral workforce artifacts. A Bundle
// contains immutable portable behavior and target requirements; it never
// contains a scope, deployment identity, resolved credential, Run history, or
// provider registration.
package bundle

import (
	"bytes"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"errors"
	"fmt"
	"regexp"
	"sort"
	"strings"
	"time"

	"github.com/axiom-studio/openseal/pkg/agent"
	"github.com/axiom-studio/openseal/pkg/capability"
	"github.com/axiom-studio/openseal/pkg/runbook"
	"github.com/axiom-studio/openseal/pkg/runtime"
	"github.com/axiom-studio/openseal/pkg/team"
	"gopkg.in/yaml.v3"
)

const (
	APIVersion = "openseal.dev/workforce-bundle/v1alpha1"
	Kind       = "WorkforceBundle"
)

var portableIDPattern = regexp.MustCompile(`^[a-z0-9][a-z0-9._-]{0,127}$`)

type Metadata struct {
	ID          string            `json:"id" yaml:"id"`
	Version     string            `json:"version" yaml:"version"`
	DisplayName string            `json:"displayName" yaml:"displayName"`
	Description string            `json:"description,omitempty" yaml:"description,omitempty"`
	Labels      map[string]string `json:"labels,omitempty" yaml:"labels,omitempty"`
}

type Compatibility struct {
	FormatRevision       int                     `json:"formatRevision" yaml:"formatRevision"`
	RequiredCapabilities []CapabilityRequirement `json:"requiredCapabilities,omitempty" yaml:"requiredCapabilities,omitempty"`
}

type CapabilityRequirement struct {
	ID      string `json:"id" yaml:"id"`
	Version int    `json:"version" yaml:"version"`
}

type Provenance struct {
	Source      string `json:"source,omitempty" yaml:"source,omitempty"`
	Reference   string `json:"reference,omitempty" yaml:"reference,omitempty"`
	CreatedBy   string `json:"createdBy,omitempty" yaml:"createdBy,omitempty"`
	DerivedFrom string `json:"derivedFrom,omitempty" yaml:"derivedFrom,omitempty"`
}

type OwnerKind string

const (
	OwnerAgent OwnerKind = "agent"
	OwnerTeam  OwnerKind = "team"
)

type OwnerReference struct {
	Kind OwnerKind `json:"kind" yaml:"kind"`
	Key  string    `json:"key" yaml:"key"`
}

type Agent struct {
	Key      string        `json:"key" yaml:"key"`
	Artifact *agent.Bundle `json:"artifact" yaml:"artifact"`
}

type RosterAssignment struct {
	ID          string `json:"id" yaml:"id"`
	RoleID      string `json:"roleId" yaml:"roleId"`
	AgentKey    string `json:"agentKey" yaml:"agentKey"`
	DisplayName string `json:"displayName,omitempty" yaml:"displayName,omitempty"`
}

type TeamDeployment struct {
	Roster       []RosterAssignment          `json:"roster" yaml:"roster"`
	Restrictions team.DeploymentRestrictions `json:"restrictions,omitempty" yaml:"restrictions,omitempty"`
}

type Team struct {
	Key        string           `json:"key" yaml:"key"`
	Definition *team.Definition `json:"definition" yaml:"definition"`
	Deployment TeamDeployment   `json:"deployment" yaml:"deployment"`
}

type Objective struct {
	Key               string                            `json:"key" yaml:"key"`
	Owner             OwnerReference                    `json:"owner" yaml:"owner"`
	Title             string                            `json:"title" yaml:"title"`
	Goal              string                            `json:"goal" yaml:"goal"`
	Status            runtime.ObjectiveStatus           `json:"status" yaml:"status"`
	Priority          int                               `json:"priority,omitempty" yaml:"priority,omitempty"`
	ExecutionPolicy   *runtime.ObjectiveExecutionPolicy `json:"executionPolicy,omitempty" yaml:"executionPolicy,omitempty"`
	Budget            *runtime.BudgetPolicy             `json:"budget,omitempty" yaml:"budget,omitempty"`
	BudgetAllocations map[string]runtime.BudgetPolicy   `json:"budgetAllocations,omitempty" yaml:"budgetAllocations,omitempty"`
	Constraints       map[string]interface{}            `json:"constraints,omitempty" yaml:"constraints,omitempty"`
	SuccessCriteria   map[string]interface{}            `json:"successCriteria,omitempty" yaml:"successCriteria,omitempty"`
}

// RunbookActivation is portable desired state. Schedule cursors, occurrence
// counters, revisions, and timestamps are intentionally regenerated by the
// importing kernel.
type RunbookActivation struct {
	Key               string                          `json:"key" yaml:"key"`
	Owner             OwnerReference                  `json:"owner" yaml:"owner"`
	ObjectiveKey      string                          `json:"objectiveKey" yaml:"objectiveKey"`
	AssignedAgentKey  string                          `json:"assignedAgentKey" yaml:"assignedAgentKey"`
	DefinitionID      string                          `json:"definitionId" yaml:"definitionId"`
	DefinitionVersion string                          `json:"definitionVersion" yaml:"definitionVersion"`
	TriggerID         string                          `json:"triggerId" yaml:"triggerId"`
	Trigger           runbook.Trigger                 `json:"trigger" yaml:"trigger"`
	Input             map[string]interface{}          `json:"input,omitempty" yaml:"input,omitempty"`
	Policy            map[string]interface{}          `json:"policy,omitempty" yaml:"policy,omitempty"`
	Budget            *runtime.BudgetPolicy           `json:"budget,omitempty" yaml:"budget,omitempty"`
	MaximumConcurrent int                             `json:"maximumConcurrent,omitempty" yaml:"maximumConcurrent,omitempty"`
	Status            runtime.RunbookActivationStatus `json:"status" yaml:"status"`
}

type Signature struct {
	Algorithm string `json:"algorithm" yaml:"algorithm"`
	KeyID     string `json:"keyId" yaml:"keyId"`
	PublicKey string `json:"publicKey" yaml:"publicKey"`
	Value     string `json:"value" yaml:"value"`
}

type Bundle struct {
	APIVersion    string              `json:"apiVersion" yaml:"apiVersion"`
	Kind          string              `json:"kind" yaml:"kind"`
	Metadata      Metadata            `json:"metadata" yaml:"metadata"`
	Compatibility Compatibility       `json:"compatibility" yaml:"compatibility"`
	Provenance    Provenance          `json:"provenance,omitempty" yaml:"provenance,omitempty"`
	Agents        []Agent             `json:"agents,omitempty" yaml:"agents,omitempty"`
	Teams         []Team              `json:"teams,omitempty" yaml:"teams,omitempty"`
	Objectives    []Objective         `json:"objectives,omitempty" yaml:"objectives,omitempty"`
	Runbooks      []RunbookActivation `json:"runbooks,omitempty" yaml:"runbooks,omitempty"`
	Digest        string              `json:"digest" yaml:"digest"`
	Signatures    []Signature         `json:"signatures,omitempty" yaml:"signatures,omitempty"`
}

func New(metadata Metadata) *Bundle {
	return &Bundle{APIVersion: APIVersion, Kind: Kind, Metadata: metadata, Compatibility: Compatibility{FormatRevision: 1}}
}

func (b *Bundle) Seal() error {
	if b == nil {
		return errors.New("workforce bundle is required")
	}
	b.Signatures = nil
	canonicalize(b)
	digest, err := contentDigest(b)
	if err != nil {
		return err
	}
	b.Digest = digest
	return b.Validate()
}

func (b *Bundle) Validate() error {
	if b == nil || b.APIVersion != APIVersion || b.Kind != Kind {
		return errors.New("workforce bundle apiVersion and kind are invalid")
	}
	if !portableIDPattern.MatchString(strings.TrimSpace(b.Metadata.ID)) || strings.TrimSpace(b.Metadata.Version) == "" || strings.TrimSpace(b.Metadata.DisplayName) == "" {
		return errors.New("workforce bundle requires a portable id, version, and display name")
	}
	if b.Compatibility.FormatRevision != 1 {
		return fmt.Errorf("workforce bundle format revision %d is unsupported", b.Compatibility.FormatRevision)
	}
	if len(b.Agents)+len(b.Teams) == 0 {
		return errors.New("workforce bundle requires at least one Agent or Team")
	}
	if err := validateLabels(b.Metadata.Labels); err != nil {
		return err
	}
	if err := validateCompatibility(b.Compatibility); err != nil {
		return err
	}
	agents := make(map[string]*agent.Bundle, len(b.Agents))
	for _, item := range b.Agents {
		if !portableIDPattern.MatchString(item.Key) || item.Artifact == nil || agents[item.Key] != nil {
			return errors.New("workforce bundle Agents require unique portable keys and artifacts")
		}
		if err := item.Artifact.Validate(); err != nil {
			return fmt.Errorf("workforce bundle Agent %s: %w", item.Key, err)
		}
		agents[item.Key] = item.Artifact
	}
	teams := make(map[string]*Team, len(b.Teams))
	for index := range b.Teams {
		item := &b.Teams[index]
		if !portableIDPattern.MatchString(item.Key) || item.Definition == nil || teams[item.Key] != nil {
			return errors.New("workforce bundle Teams require unique portable keys and definitions")
		}
		if err := item.Definition.Validate(); err != nil {
			return fmt.Errorf("workforce bundle Team %s: %w", item.Key, err)
		}
		if err := validateTeamDeployment(item, agents); err != nil {
			return err
		}
		teams[item.Key] = item
	}
	objectives := make(map[string]Objective, len(b.Objectives))
	for _, item := range b.Objectives {
		if !portableIDPattern.MatchString(item.Key) || objectives[item.Key].Key != "" || !ownerExists(item.Owner, agents, teams) {
			return errors.New("workforce bundle Objectives require unique keys and existing owners")
		}
		probe := &runtime.Objective{
			ID: item.Key, Scope: runtime.Scope{Kind: "portable", ID: "bundle"}, Owner: runtime.ObjectiveOwner{Type: runtime.OwnerType(item.Owner.Kind), ID: item.Owner.Key},
			Title: item.Title, Goal: item.Goal, Status: item.Status, Priority: item.Priority, ExecutionPolicy: item.ExecutionPolicy,
			Budget: item.Budget, BudgetAllocations: item.BudgetAllocations, Constraints: item.Constraints, SuccessCriteria: item.SuccessCriteria,
			Revision: 1, CreatedAt: time.Unix(1, 0).UTC(), UpdatedAt: time.Unix(1, 0).UTC(),
		}
		if err := probe.Validate(); err != nil {
			return fmt.Errorf("workforce bundle Objective %s: %w", item.Key, err)
		}
		if err := validateSecretFree(item.Constraints, "objectives."+item.Key+".constraints"); err != nil {
			return err
		}
		if err := validateSecretFree(item.SuccessCriteria, "objectives."+item.Key+".successCriteria"); err != nil {
			return err
		}
		objectives[item.Key] = item
	}
	runbooks := make(map[string]bool, len(b.Runbooks))
	for _, item := range b.Runbooks {
		if !portableIDPattern.MatchString(item.Key) || runbooks[item.Key] || !ownerExists(item.Owner, agents, teams) || objectives[item.ObjectiveKey].Key == "" || agents[item.AssignedAgentKey] == nil {
			return errors.New("workforce bundle Runbooks require unique keys and existing owner, Objective, and assigned Agent references")
		}
		if objectives[item.ObjectiveKey].Owner != item.Owner {
			return fmt.Errorf("workforce bundle Runbook %s owner does not match Objective %s", item.Key, item.ObjectiveKey)
		}
		manifestRunbook := agents[item.AssignedAgentKey].Agent.Spec.Runbook
		if manifestRunbook == nil || manifestRunbook.ID != item.DefinitionID || manifestRunbook.Version != item.DefinitionVersion {
			return fmt.Errorf("workforce bundle Runbook %s is not supplied by assigned Agent %s", item.Key, item.AssignedAgentKey)
		}
		trigger, ok := manifestRunbook.Triggers[item.TriggerID]
		if !ok || !jsonEqual(trigger, item.Trigger) {
			return fmt.Errorf("workforce bundle Runbook %s trigger differs from its immutable Agent definition", item.Key)
		}
		probe := &runtime.RunbookActivation{
			ID: item.Key, Scope: runtime.Scope{Kind: "portable", ID: "bundle"}, Owner: runtime.ObjectiveOwner{Type: runtime.OwnerType(item.Owner.Kind), ID: item.Owner.Key},
			ObjectiveID: item.ObjectiveKey, AssignedAgentID: item.AssignedAgentKey, DefinitionID: item.DefinitionID, DefinitionVersion: item.DefinitionVersion,
			TriggerID: item.TriggerID, Trigger: item.Trigger, Input: item.Input, Policy: item.Policy, Budget: item.Budget,
			MaximumConcurrent: item.MaximumConcurrent, Status: item.Status, Revision: 1, CreatedAt: time.Unix(1, 0).UTC(), UpdatedAt: time.Unix(1, 0).UTC(),
		}
		if err := probe.Validate(); err != nil {
			return fmt.Errorf("workforce bundle Runbook %s: %w", item.Key, err)
		}
		if err := validateSecretFree(item.Input, "runbooks."+item.Key+".input"); err != nil {
			return err
		}
		if err := validateSecretFree(item.Policy, "runbooks."+item.Key+".policy"); err != nil {
			return err
		}
		runbooks[item.Key] = true
	}
	want, err := contentDigest(b)
	if err != nil {
		return err
	}
	if b.Digest != want {
		return errors.New("workforce bundle digest does not match its portable content")
	}
	return validateSignatureShapes(b.Signatures)
}

func validateTeamDeployment(item *Team, agents map[string]*agent.Bundle) error {
	roster := make([]team.RosterAssignment, 0, len(item.Deployment.Roster))
	for _, assignment := range item.Deployment.Roster {
		if !portableIDPattern.MatchString(assignment.ID) || agents[assignment.AgentKey] == nil {
			return fmt.Errorf("workforce bundle Team %s roster references an unknown Agent", item.Key)
		}
		roster = append(roster, team.RosterAssignment{ID: assignment.ID, RoleID: assignment.RoleID, AgentDeploymentID: assignment.AgentKey, DisplayName: assignment.DisplayName})
	}
	probe := &team.Deployment{
		ID: item.Key, Scope: capability.ScopeReference{Kind: "portable", ID: "bundle"}, DefinitionID: item.Definition.ID,
		ActiveVersion: item.Definition.Version, Roster: roster, Restrictions: item.Deployment.Restrictions,
		Status: team.DeploymentActive, Revision: 1, CreatedAt: time.Unix(1, 0).UTC(), UpdatedAt: time.Unix(1, 0).UTC(),
	}
	if err := probe.Validate(item.Definition); err != nil {
		return fmt.Errorf("workforce bundle Team %s deployment: %w", item.Key, err)
	}
	return nil
}

func ownerExists(owner OwnerReference, agents map[string]*agent.Bundle, teams map[string]*Team) bool {
	switch owner.Kind {
	case OwnerAgent:
		return agents[owner.Key] != nil
	case OwnerTeam:
		return teams[owner.Key] != nil
	default:
		return false
	}
}

func validateLabels(labels map[string]string) error {
	for key, value := range labels {
		if !portableIDPattern.MatchString(key) || strings.TrimSpace(value) != value || len(value) > 256 {
			return errors.New("workforce bundle labels require portable keys and bounded normalized values")
		}
	}
	return nil
}

func validateCompatibility(value Compatibility) error {
	seen := map[string]bool{}
	for _, requirement := range value.RequiredCapabilities {
		if !portableIDPattern.MatchString(requirement.ID) || requirement.Version < 1 || seen[requirement.ID] {
			return errors.New("workforce bundle capabilities require unique portable ids and positive versions")
		}
		seen[requirement.ID] = true
	}
	return nil
}

func canonicalize(bundle *Bundle) {
	if bundle == nil {
		return
	}
	sort.Slice(bundle.Compatibility.RequiredCapabilities, func(i, j int) bool {
		return bundle.Compatibility.RequiredCapabilities[i].ID < bundle.Compatibility.RequiredCapabilities[j].ID
	})
	sort.Slice(bundle.Agents, func(i, j int) bool { return bundle.Agents[i].Key < bundle.Agents[j].Key })
	sort.Slice(bundle.Teams, func(i, j int) bool { return bundle.Teams[i].Key < bundle.Teams[j].Key })
	for index := range bundle.Teams {
		sort.Slice(bundle.Teams[index].Deployment.Roster, func(i, j int) bool {
			return bundle.Teams[index].Deployment.Roster[i].ID < bundle.Teams[index].Deployment.Roster[j].ID
		})
	}
	sort.Slice(bundle.Objectives, func(i, j int) bool { return bundle.Objectives[i].Key < bundle.Objectives[j].Key })
	sort.Slice(bundle.Runbooks, func(i, j int) bool { return bundle.Runbooks[i].Key < bundle.Runbooks[j].Key })
	sort.Slice(bundle.Signatures, func(i, j int) bool { return bundle.Signatures[i].KeyID < bundle.Signatures[j].KeyID })
}

func contentDigest(bundle *Bundle) (string, error) {
	copy, err := clone(bundle)
	if err != nil {
		return "", err
	}
	copy.Digest, copy.Signatures = "", nil
	canonicalize(copy)
	encoded, err := json.Marshal(copy)
	if err != nil {
		return "", fmt.Errorf("encode workforce bundle digest: %w", err)
	}
	digest := sha256.Sum256(encoded)
	return "sha256:" + hex.EncodeToString(digest[:]), nil
}

func clone(bundle *Bundle) (*Bundle, error) {
	if bundle == nil {
		return nil, errors.New("workforce bundle is required")
	}
	encoded, err := json.Marshal(bundle)
	if err != nil {
		return nil, err
	}
	var result Bundle
	if err := json.Unmarshal(encoded, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func EncodeYAML(bundle *Bundle) ([]byte, error) {
	if err := bundle.Validate(); err != nil {
		return nil, err
	}
	encoded, err := json.Marshal(bundle)
	if err != nil {
		return nil, err
	}
	var value map[string]interface{}
	if err := json.Unmarshal(encoded, &value); err != nil {
		return nil, err
	}
	return yaml.Marshal(value)
}

func DecodeYAML(data []byte) (*Bundle, error) {
	var value map[string]interface{}
	if err := yaml.Unmarshal(data, &value); err != nil {
		return nil, fmt.Errorf("decode workforce bundle YAML: %w", err)
	}
	encoded, err := json.Marshal(value)
	if err != nil {
		return nil, err
	}
	decoder := json.NewDecoder(bytes.NewReader(encoded))
	decoder.DisallowUnknownFields()
	var result Bundle
	if err := decoder.Decode(&result); err != nil {
		return nil, fmt.Errorf("decode workforce bundle contract: %w", err)
	}
	if err := result.Validate(); err != nil {
		return nil, err
	}
	return &result, nil
}

func jsonEqual(left, right interface{}) bool {
	leftJSON, leftErr := json.Marshal(left)
	rightJSON, rightErr := json.Marshal(right)
	return leftErr == nil && rightErr == nil && bytes.Equal(leftJSON, rightJSON)
}

func validateSecretFree(value interface{}, path string) error {
	if value == nil {
		return nil
	}
	encoded, err := json.Marshal(value)
	if err != nil {
		return fmt.Errorf("%s: %w", path, err)
	}
	var normalized interface{}
	if err := json.Unmarshal(encoded, &normalized); err != nil {
		return fmt.Errorf("%s: %w", path, err)
	}
	return walkSecretFree(normalized, path)
}

func walkSecretFree(value interface{}, path string) error {
	switch typed := value.(type) {
	case map[string]interface{}:
		for key, child := range typed {
			normalized := strings.ToLower(strings.NewReplacer("_", "", "-", "", ".", "").Replace(key))
			for _, forbidden := range []string{"password", "passwd", "secret", "token", "apikey", "authorization", "privatekey", "credentialvalue"} {
				if strings.Contains(normalized, forbidden) {
					return fmt.Errorf("%s.%s contains secret-shaped material", path, key)
				}
			}
			if err := walkSecretFree(child, path+"."+key); err != nil {
				return err
			}
		}
	case []interface{}:
		for index, child := range typed {
			if err := walkSecretFree(child, fmt.Sprintf("%s[%d]", path, index)); err != nil {
				return err
			}
		}
	case string:
		lower := strings.ToLower(strings.TrimSpace(typed))
		if strings.HasPrefix(lower, "vault://") || strings.HasPrefix(lower, "secret://") || strings.HasPrefix(lower, "bearer ") {
			return fmt.Errorf("%s contains a host-local credential or secret", path)
		}
	}
	return nil
}
