{{- if and .Values.metrics.enabled .Values.metrics.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "openseal.fullname" . }}
  labels:
    {{- include "openseal.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "openseal.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: metrics
      path: {{ .Values.metrics.path }}
      interval: 30s
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
{{- end }}
