apiVersion: v1
kind: Service
metadata:
  name: {{ include "openseal.fullname" . }}
  labels:
    {{- include "openseal.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.healthCheck.port }}
      targetPort: health
      protocol: TCP
      name: health
  selector:
    {{- include "openseal.selectorLabels" . | nindent 4 }}
