package agent

import (
	"bytes"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"errors"
	"fmt"
	"sort"
	"strings"

	"github.com/axiom-studio/openseal/pkg/capability"
	"gopkg.in/yaml.v3"
)

const (
	BundleAPIVersion = "openseal.dev/agent-bundle/v1alpha1"
	BundleKind       = "AgentBundle"
)

// Bundle is the complete portable installation artifact for one Agent. The
// Manifest owns behavior; Requirements describe what an installing host must
// resolve without carrying source-host credentials or provider identifiers.
type Bundle struct {
	APIVersion  string                   `json:"apiVersion" yaml:"apiVersion"`
	Kind        string                   `json:"kind" yaml:"kind"`
	Metadata    BundleMetadata           `json:"metadata" yaml:"metadata"`
	Agent       *Manifest                `json:"agent" yaml:"agent"`
	Policy      BundleDeploymentPolicy   `json:"policy,omitempty" yaml:"policy,omitempty"`
	Skills      []BundleSkillRequirement `json:"skills,omitempty" yaml:"skills,omitempty"`
	Credentials []BundleCredentialNeed   `json:"credentials,omitempty" yaml:"credentials,omitempty"`
	Endpoints   []BundleEndpointNeed     `json:"endpoints,omitempty" yaml:"endpoints,omitempty"`
	Digest      string                   `json:"digest" yaml:"digest"`
}

type BundleMetadata struct {
	ID          string   `json:"id" yaml:"id"`
	Version     string   `json:"version" yaml:"version"`
	DisplayName string   `json:"displayName" yaml:"displayName"`
	Description string   `json:"description,omitempty" yaml:"description,omitempty"`
	Tags        []string `json:"tags,omitempty" yaml:"tags,omitempty"`
}

// BundleDeploymentPolicy preserves portable narrowing and capacity. Scope,
// environment, rollout status, health, and placement remain host-owned.
type BundleDeploymentPolicy struct {
	Restrictions DeploymentRestrictions `json:"restrictions,omitempty" yaml:"restrictions,omitempty"`
	Capacity     DeploymentCapacity     `json:"capacity" yaml:"capacity"`
}

// BundleSkillRequirement pins the reviewed immutable Skill identity selected
// for one catalog requirement. Source identity is part of authority and must
// survive registry changes between hosts.
type BundleSkillRequirement struct {
	RequirementID string                   `json:"requirementId" yaml:"requirementId"`
	Identity      capability.SkillIdentity `json:"identity" yaml:"identity"`
	Policy        BundleSkillPolicy        `json:"policy" yaml:"policy"`
}

type BundleSkillPolicy struct {
	AllowedActions              []string                                      `json:"allowedActions" yaml:"allowedActions"`
	EnablePrompt                bool                                          `json:"enablePrompt,omitempty" yaml:"enablePrompt,omitempty"`
	EnabledConversationAdapters []string                                      `json:"enabledConversationAdapters,omitempty" yaml:"enabledConversationAdapters,omitempty"`
	EnabledCallbackAdapters     []string                                      `json:"enabledCallbackAdapters,omitempty" yaml:"enabledCallbackAdapters,omitempty"`
	MaximumRisk                 capability.RiskLevel                          `json:"maximumRisk" yaml:"maximumRisk"`
	ArgumentRestrictions        map[string]map[string]capability.ArgumentRule `json:"argumentRestrictions,omitempty" yaml:"argumentRestrictions,omitempty"`
	Config                      map[string]interface{}                        `json:"config,omitempty" yaml:"config,omitempty"`
}

// BundleCredentialNeed is a logical secret slot, never a credential binding.
// RequiredBy contains Skill requirement IDs or the reserved value "agent" for
// an AgentDeployment credential such as its model provider.
type BundleCredentialNeed struct {
	Name       string   `json:"name" yaml:"name"`
	BindingKey string   `json:"bindingKey" yaml:"bindingKey"`
	Kind       string   `json:"kind" yaml:"kind"`
	Optional   bool     `json:"optional,omitempty" yaml:"optional,omitempty"`
	RequiredBy []string `json:"requiredBy" yaml:"requiredBy"`
}

// BundleEndpointNeed preserves logical workflow routing intent. Destination,
// provider installation, binding, application identity, and callback ingress
// are deliberately resolved and regenerated by the target host.
type BundleEndpointNeed struct {
	ID        string                              `json:"id" yaml:"id"`
	Name      string                              `json:"name" yaml:"name"`
	Provider  string                              `json:"provider" yaml:"provider"`
	Mode      capability.ConversationEndpointMode `json:"mode" yaml:"mode"`
	Adapter   capability.SkillIdentity            `json:"adapter" yaml:"adapter"`
	AdapterID string                              `json:"adapterId" yaml:"adapterId"`
	Enabled   bool                                `json:"enabled,omitempty" yaml:"enabled,omitempty"`
}

type BundleExportRequest struct {
	Definition  *AgentDefinition
	Deployment  *AgentDeployment
	EndpointIDs map[string]string
	Metadata    BundleMetadata
	Manifest    ManifestMetadata
	Skills      []BundleSkillRequirement
	Credentials []BundleCredentialNeed
	Endpoints   []BundleEndpointNeed
}

type BundleSkillPlacement struct {
	Identity  capability.SkillIdentity `json:"identity"`
	BindingID string                   `json:"bindingId"`
}

type BundleEndpointPlacement struct {
	Provider       string                   `json:"provider"`
	Adapter        capability.SkillIdentity `json:"adapter"`
	BindingID      string                   `json:"bindingId"`
	InstallationID string                   `json:"installationId,omitempty"`
	ApplicationID  string                   `json:"applicationId,omitempty"`
	Address        string                   `json:"address"`
}

// BundlePlacement contains only target-host choices. It is never serialized
// into the portable artifact and may contain opaque credential references.
type BundlePlacement struct {
	DeploymentID string                                    `json:"deploymentId"`
	Environment  string                                    `json:"environment"`
	Skills       map[string]BundleSkillPlacement           `json:"skills,omitempty"`
	Credentials  map[string]capability.CredentialReference `json:"credentials,omitempty"`
	Endpoints    map[string]BundleEndpointPlacement        `json:"endpoints,omitempty"`
}

type BundleRequirementKind string

const (
	BundleRequirementSkill      BundleRequirementKind = "skill"
	BundleRequirementCredential BundleRequirementKind = "credential"
	BundleRequirementEndpoint   BundleRequirementKind = "endpoint"
	BundleRequirementDeployment BundleRequirementKind = "deployment"
)

type BundleRequirementResolution struct {
	Kind     BundleRequirementKind `json:"kind"`
	ID       string                `json:"id"`
	Required bool                  `json:"required"`
	Resolved bool                  `json:"resolved"`
	Message  string                `json:"message,omitempty"`
}

type BundleInstallationPreview struct {
	BundleDigest string                        `json:"bundleDigest"`
	Ready        bool                          `json:"ready"`
	Requirements []BundleRequirementResolution `json:"requirements"`
}

type BundleInstallationRequest struct {
	Bundle         *Bundle
	Scope          capability.ScopeReference
	Placement      BundlePlacement
	ActorType      string
	ActorID        string
	Reason         string
	IdempotencyKey string
}

// BundleEndpointInstallation is provider-neutral desired state for the target
// host to materialize. Callback routes and ingress URLs are intentionally not
// accepted from the source artifact or caller.
type BundleEndpointInstallation struct {
	Requirement BundleEndpointNeed      `json:"requirement"`
	Placement   BundleEndpointPlacement `json:"placement"`
}

type BundleInstallationPlan struct {
	Manifest  ManifestInstallationRequest  `json:"manifest"`
	Bindings  []*capability.Binding        `json:"bindings,omitempty"`
	Endpoints []BundleEndpointInstallation `json:"endpoints,omitempty"`
}

// ExportBundle projects reviewed portable state into a deterministic artifact.
// The caller supplies host-derived requirements after stripping every binding;
// this package validates that they exactly cover the immutable definition.
func ExportBundle(request BundleExportRequest) (*Bundle, error) {
	if request.Definition == nil || request.Deployment == nil {
		return nil, errors.New("agent definition and deployment are required")
	}
	manifest, err := ExportManifest(ManifestExportRequest{
		Definition: request.Definition, DeploymentID: request.Deployment.ID, EndpointIDs: request.EndpointIDs, Metadata: request.Manifest,
	})
	if err != nil {
		return nil, err
	}
	metadata := request.Metadata
	if metadata.ID == "" {
		metadata.ID = manifest.Metadata.ID
	}
	if metadata.Version == "" {
		metadata.Version = manifest.Metadata.Version
	}
	if metadata.DisplayName == "" {
		metadata.DisplayName = manifest.Metadata.DisplayName
	}
	if metadata.Description == "" {
		metadata.Description = manifest.Metadata.Description
	}
	bundle := &Bundle{
		APIVersion: BundleAPIVersion, Kind: BundleKind, Metadata: metadata, Agent: manifest,
		Policy: BundleDeploymentPolicy{Restrictions: request.Deployment.Restrictions, Capacity: request.Deployment.Capacity},
		Skills: request.Skills, Credentials: request.Credentials, Endpoints: request.Endpoints,
	}
	canonicalizeBundle(bundle)
	bundle.Digest, err = bundleDigest(bundle)
	if err != nil {
		return nil, err
	}
	if err = bundle.Validate(); err != nil {
		return nil, err
	}
	return bundle, nil
}

// PreviewBundleInstallation compares one portable bundle with target-host
// choices without writing any state. Every unresolved or mismatched authority
// boundary is returned as a typed requirement for Studio, TUI, and API clients.
func PreviewBundleInstallation(bundle *Bundle, placement BundlePlacement) (*BundleInstallationPreview, error) {
	if err := bundle.Validate(); err != nil {
		return nil, err
	}
	preview := &BundleInstallationPreview{BundleDigest: bundle.Digest, Ready: true}
	appendResolution := func(value BundleRequirementResolution) {
		preview.Requirements = append(preview.Requirements, value)
		if value.Required && !value.Resolved {
			preview.Ready = false
		}
	}
	appendResolution(BundleRequirementResolution{
		Kind: BundleRequirementDeployment, ID: "target", Required: true,
		Resolved: strings.TrimSpace(placement.DeploymentID) != "" && strings.TrimSpace(placement.Environment) != "",
		Message:  "Choose a target Agent identity and environment.",
	})
	for _, need := range bundle.Skills {
		selected, ok := placement.Skills[need.RequirementID]
		resolved := ok && selected.Identity.Equal(need.Identity) && strings.TrimSpace(selected.BindingID) != ""
		appendResolution(BundleRequirementResolution{
			Kind: BundleRequirementSkill, ID: need.RequirementID, Required: !bundleSkillOptional(bundle.Agent, need.RequirementID), Resolved: resolved,
			Message: "Install and bind the exact reviewed Skill source and version.",
		})
	}
	for _, need := range bundle.Credentials {
		selected, ok := placement.Credentials[need.Name]
		resolved := ok && strings.TrimSpace(selected.Kind) == need.Kind && strings.TrimSpace(selected.ID) != ""
		appendResolution(BundleRequirementResolution{
			Kind: BundleRequirementCredential, ID: need.Name, Required: !need.Optional, Resolved: resolved,
			Message: "Choose an authorized target credential; secret values never enter the bundle.",
		})
	}
	for _, need := range bundle.Endpoints {
		selected, ok := placement.Endpoints[need.ID]
		resolved := ok && strings.TrimSpace(selected.Provider) == need.Provider && selected.Adapter.Equal(need.Adapter) &&
			strings.TrimSpace(selected.BindingID) != "" && strings.TrimSpace(selected.Address) != ""
		if resolved {
			adapterBound := false
			for _, skill := range placement.Skills {
				if skill.Identity.Equal(selected.Adapter) && skill.BindingID == selected.BindingID {
					adapterBound = true
					break
				}
			}
			resolved = adapterBound
		}
		appendResolution(BundleRequirementResolution{
			Kind: BundleRequirementEndpoint, ID: need.ID, Required: true, Resolved: resolved,
			Message: "Choose a destination visible to the authorized provider connection.",
		})
	}
	sort.Slice(preview.Requirements, func(i, j int) bool {
		left, right := preview.Requirements[i], preview.Requirements[j]
		return string(left.Kind)+"\x00"+left.ID < string(right.Kind)+"\x00"+right.ID
	})
	return preview, nil
}

// CompileBundleInstallation turns a ready preview into one idempotent Agent
// manifest installation and provider-neutral endpoint plan. Applying these is
// a separate host transaction; this compiler performs no writes.
func CompileBundleInstallation(request BundleInstallationRequest) (*BundleInstallationPlan, error) {
	preview, err := PreviewBundleInstallation(request.Bundle, request.Placement)
	if err != nil {
		return nil, err
	}
	if !preview.Ready {
		return nil, errors.New("agent bundle installation has unresolved target requirements")
	}
	if strings.TrimSpace(request.Scope.Kind) == "" || strings.TrimSpace(request.Scope.ID) == "" || strings.TrimSpace(request.ActorType) == "" || strings.TrimSpace(request.ActorID) == "" || strings.TrimSpace(request.IdempotencyKey) == "" {
		return nil, errors.New("agent bundle installation requires scope, actor, and idempotency key")
	}
	definition, err := CompileManifest(request.Bundle.Agent, request.Bundle.Agent.Metadata.ID, DefinitionProvenance{})
	if err != nil {
		return nil, err
	}
	capacity := request.Bundle.Policy.Capacity
	if capacity.MaxConcurrentRuns == 0 {
		capacity.MaxConcurrentRuns = definition.Authority.MaxConcurrentRuns
	}
	bindingSet := map[string]bool{}
	for _, selected := range request.Placement.Skills {
		bindingSet[selected.BindingID] = true
	}
	bindingIDs := make([]string, 0, len(bindingSet))
	for id := range bindingSet {
		bindingIDs = append(bindingIDs, id)
	}
	sort.Strings(bindingIDs)
	deploymentCredentials := map[string]capability.CredentialReference{}
	bindingCredentials := map[string]map[string]capability.CredentialReference{}
	for _, need := range request.Bundle.Credentials {
		reference, resolved := request.Placement.Credentials[need.Name]
		if !resolved {
			continue
		}
		for _, consumer := range need.RequiredBy {
			if consumer == "agent" {
				deploymentCredentials[need.BindingKey] = reference
				continue
			}
			if bindingCredentials[consumer] == nil {
				bindingCredentials[consumer] = map[string]capability.CredentialReference{}
			}
			bindingCredentials[consumer][need.BindingKey] = reference
		}
	}
	deployment := &AgentDeployment{
		ID: request.Placement.DeploymentID, DisplayName: request.Bundle.Agent.Metadata.DisplayName,
		Scope: request.Scope, RolloutStatus: RolloutActive, Environment: request.Placement.Environment,
		SkillBindingIDs: bindingIDs, Credentials: deploymentCredentials,
		Restrictions: request.Bundle.Policy.Restrictions, Capacity: capacity,
	}
	plan := &BundleInstallationPlan{Manifest: ManifestInstallationRequest{
		Manifest: request.Bundle.Agent, Deployment: deployment, ActorType: strings.TrimSpace(request.ActorType), ActorID: strings.TrimSpace(request.ActorID),
		Reason: strings.TrimSpace(request.Reason), IdempotencyKey: strings.TrimSpace(request.IdempotencyKey),
	}}
	for _, need := range request.Bundle.Skills {
		selected := request.Placement.Skills[need.RequirementID]
		plan.Bindings = append(plan.Bindings, &capability.Binding{
			ID: selected.BindingID, Scope: request.Scope, DeploymentID: request.Placement.DeploymentID,
			SkillID: need.Identity.ID, SkillVersion: need.Identity.Version, SourceIdentity: need.Identity.SourceIdentity,
			AllowedActions: append([]string(nil), need.Policy.AllowedActions...), EnablePrompt: need.Policy.EnablePrompt,
			EnabledConversationAdapters: append([]string(nil), need.Policy.EnabledConversationAdapters...),
			EnabledCallbackAdapters:     append([]string(nil), need.Policy.EnabledCallbackAdapters...),
			MaximumRisk:                 need.Policy.MaximumRisk, ArgumentRestrictions: need.Policy.ArgumentRestrictions,
			Credentials: cloneCredentialReferences(bindingCredentials[need.RequirementID]), Config: need.Policy.Config,
		})
	}
	for _, need := range request.Bundle.Endpoints {
		plan.Endpoints = append(plan.Endpoints, BundleEndpointInstallation{Requirement: need, Placement: request.Placement.Endpoints[need.ID]})
	}
	return plan, nil
}

func bundleSkillOptional(manifest *Manifest, id string) bool {
	if manifest == nil {
		return false
	}
	for _, requirement := range manifest.Spec.SkillRequirements {
		if requirement.SkillID == id {
			return requirement.Optional
		}
	}
	return false
}

func cloneCredentialReferences(values map[string]capability.CredentialReference) map[string]capability.CredentialReference {
	if values == nil {
		return nil
	}
	copy := make(map[string]capability.CredentialReference, len(values))
	for name, reference := range values {
		copy[name] = reference
	}
	return copy
}

func (b *Bundle) Validate() error {
	if b == nil || b.APIVersion != BundleAPIVersion || b.Kind != BundleKind || b.Agent == nil {
		return errors.New("agent bundle apiVersion, kind, and agent are required")
	}
	if !manifestIDPattern.MatchString(strings.TrimSpace(b.Metadata.ID)) || !versionPattern.MatchString(strings.TrimSpace(b.Metadata.Version)) || strings.TrimSpace(b.Metadata.DisplayName) == "" {
		return errors.New("agent bundle requires a valid id, version, and display name")
	}
	if b.Metadata.Version != b.Agent.Metadata.Version {
		return errors.New("agent bundle and manifest versions must match")
	}
	definition, err := CompileManifest(b.Agent, b.Agent.Metadata.ID, DefinitionProvenance{})
	if err != nil {
		return fmt.Errorf("agent bundle manifest: %w", err)
	}
	deployment := &AgentDeployment{
		ID: "portable-validation", Scope: capability.ScopeReference{Kind: "portable", ID: "validation"},
		DefinitionID: definition.ID, ActiveVersion: definition.Version, RolloutStatus: RolloutActive,
		Environment: "portable", Restrictions: b.Policy.Restrictions, Capacity: b.Policy.Capacity, Revision: 1,
	}
	if deployment.Capacity.MaxConcurrentRuns == 0 {
		deployment.Capacity.MaxConcurrentRuns = definition.Authority.MaxConcurrentRuns
	}
	if err = deployment.Validate(); err != nil {
		return fmt.Errorf("agent bundle deployment policy: %w", err)
	}
	if err = validateNarrowing(definition, deployment); err != nil {
		return fmt.Errorf("agent bundle deployment policy: %w", err)
	}

	declaredSkills := make(map[string]SkillRequirement, len(definition.SkillRequirements))
	for _, requirement := range definition.SkillRequirements {
		declaredSkills[requirement.SkillID] = requirement
	}
	resolvedSkills := make(map[string]capability.SkillIdentity, len(b.Skills))
	for _, requirement := range b.Skills {
		id := strings.TrimSpace(requirement.RequirementID)
		identity := requirement.Identity.Normalized()
		if _, ok := declaredSkills[id]; !ok || !identity.Valid() || resolvedSkills[id].Valid() {
			return errors.New("agent bundle Skills must uniquely resolve declared manifest requirements")
		}
		if !validRisk(requirement.Policy.MaximumRisk) || riskRank(requirement.Policy.MaximumRisk) > riskRank(definition.Authority.MaximumRisk) {
			return fmt.Errorf("agent bundle Skill %s policy exceeds Agent risk authority", id)
		}
		allowedActions := map[string]bool{}
		for _, action := range requirement.Policy.AllowedActions {
			if strings.TrimSpace(action) == "" || allowedActions[action] {
				return fmt.Errorf("agent bundle Skill %s policy has invalid or duplicate actions", id)
			}
			allowedActions[action] = true
		}
		for _, action := range declaredSkills[id].RequiredActions {
			if !allowedActions[action] {
				return fmt.Errorf("agent bundle Skill %s policy omits required action %s", id, action)
			}
		}
		if declaredSkills[id].PromptRequired && !requirement.Policy.EnablePrompt {
			return fmt.Errorf("agent bundle Skill %s policy omits its required prompt", id)
		}
		if err := validateNoSecrets(requirement.Policy.Config, "skills."+id+".policy.config"); err != nil {
			return err
		}
		resolvedSkills[id] = identity
	}
	for id, requirement := range declaredSkills {
		if !requirement.Optional && !resolvedSkills[id].Valid() {
			return fmt.Errorf("agent bundle is missing required Skill %s", id)
		}
	}

	credentialNames := map[string]bool{}
	for _, need := range b.Credentials {
		name, bindingKey, kind := strings.TrimSpace(need.Name), strings.TrimSpace(need.BindingKey), strings.TrimSpace(need.Kind)
		if name == "" || bindingKey == "" || kind == "" || credentialNames[name] || len(need.RequiredBy) == 0 {
			return errors.New("agent bundle credentials require unique names, binding keys, kinds, and consumers")
		}
		credentialNames[name] = true
		for _, consumer := range need.RequiredBy {
			if consumer != "agent" && declaredSkills[consumer].SkillID == "" {
				return fmt.Errorf("agent bundle credential %s references unknown consumer %s", name, consumer)
			}
		}
	}

	channels := make(map[string]bool, len(definition.Channels))
	for _, channel := range definition.Channels {
		channels[channel.EndpointID] = true
	}
	endpointIDs := map[string]bool{}
	for _, endpoint := range b.Endpoints {
		id := strings.TrimSpace(endpoint.ID)
		adapter := endpoint.Adapter.Normalized()
		if !channels[id] || endpointIDs[id] || strings.TrimSpace(endpoint.Name) == "" || strings.TrimSpace(endpoint.Provider) == "" || !adapter.Valid() || strings.TrimSpace(endpoint.AdapterID) == "" || (endpoint.Mode != capability.ConversationEndpointChannel && endpoint.Mode != capability.ConversationEndpointDirect) {
			return errors.New("agent bundle endpoints must uniquely resolve declared channel routes")
		}
		adapterDeclared := false
		for _, identity := range resolvedSkills {
			if identity.Equal(adapter) {
				adapterDeclared = true
				break
			}
		}
		if !adapterDeclared {
			return fmt.Errorf("agent bundle endpoint %s adapter is not a resolved Agent Skill", id)
		}
		endpointIDs[id] = true
	}
	for id := range channels {
		if !endpointIDs[id] {
			return fmt.Errorf("agent bundle is missing endpoint requirement %s", id)
		}
	}
	wantDigest, err := bundleDigest(b)
	if err != nil {
		return err
	}
	if b.Digest != wantDigest {
		return errors.New("agent bundle digest does not match its portable content")
	}
	return nil
}

func EncodeBundleYAML(bundle *Bundle) ([]byte, error) {
	if err := bundle.Validate(); err != nil {
		return nil, err
	}
	jsonDocument, err := json.Marshal(bundle)
	if err != nil {
		return nil, err
	}
	var document map[string]interface{}
	if err = json.Unmarshal(jsonDocument, &document); err != nil {
		return nil, err
	}
	return yaml.Marshal(document)
}

func DecodeBundleYAML(data []byte) (*Bundle, error) {
	var document map[string]interface{}
	if err := yaml.Unmarshal(data, &document); err != nil {
		return nil, fmt.Errorf("decode agent bundle YAML: %w", err)
	}
	encoded, err := json.Marshal(document)
	if err != nil {
		return nil, err
	}
	decoder := json.NewDecoder(bytes.NewReader(encoded))
	decoder.DisallowUnknownFields()
	var bundle Bundle
	if err = decoder.Decode(&bundle); err != nil {
		return nil, fmt.Errorf("decode agent bundle contract: %w", err)
	}
	if err = bundle.Validate(); err != nil {
		return nil, err
	}
	return &bundle, nil
}

func canonicalizeBundle(bundle *Bundle) {
	if bundle == nil {
		return
	}
	sort.Strings(bundle.Metadata.Tags)
	sort.Slice(bundle.Skills, func(i, j int) bool { return bundle.Skills[i].RequirementID < bundle.Skills[j].RequirementID })
	for index := range bundle.Credentials {
		sort.Strings(bundle.Credentials[index].RequiredBy)
	}
	sort.Slice(bundle.Credentials, func(i, j int) bool { return bundle.Credentials[i].Name < bundle.Credentials[j].Name })
	sort.Slice(bundle.Endpoints, func(i, j int) bool { return bundle.Endpoints[i].ID < bundle.Endpoints[j].ID })
}

func bundleDigest(bundle *Bundle) (string, error) {
	if bundle == nil {
		return "", errors.New("agent bundle is required")
	}
	copy := *bundle
	copy.Digest = ""
	encoded, err := json.Marshal(copy)
	if err != nil {
		return "", fmt.Errorf("encode agent bundle digest: %w", err)
	}
	digest := sha256.Sum256(encoded)
	return "sha256:" + hex.EncodeToString(digest[:]), nil
}
