package agent

import (
	"bytes"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"errors"
	"fmt"
	"sort"
	"strings"

	"github.com/axiom-studio/openseal/pkg/capability"
	"gopkg.in/yaml.v3"
)

const (
	BundleAPIVersion = "openseal.dev/agent-bundle/v1alpha1"
	BundleKind       = "AgentBundle"
)

// Bundle is the complete portable installation artifact for one Agent. The
// Manifest owns behavior; Requirements describe what an installing host must
// resolve without carrying source-host credentials or provider identifiers.
type Bundle struct {
	APIVersion  string                   `json:"apiVersion" yaml:"apiVersion"`
	Kind        string                   `json:"kind" yaml:"kind"`
	Metadata    BundleMetadata           `json:"metadata" yaml:"metadata"`
	Agent       *Manifest                `json:"agent" yaml:"agent"`
	Policy      BundleDeploymentPolicy   `json:"policy,omitempty" yaml:"policy,omitempty"`
	Skills      []BundleSkillRequirement `json:"skills,omitempty" yaml:"skills,omitempty"`
	Credentials []BundleCredentialNeed   `json:"credentials,omitempty" yaml:"credentials,omitempty"`
	Endpoints   []BundleEndpointNeed     `json:"endpoints,omitempty" yaml:"endpoints,omitempty"`
	Digest      string                   `json:"digest" yaml:"digest"`
}

type BundleMetadata struct {
	ID          string   `json:"id" yaml:"id"`
	Version     string   `json:"version" yaml:"version"`
	DisplayName string   `json:"displayName" yaml:"displayName"`
	Description string   `json:"description,omitempty" yaml:"description,omitempty"`
	Tags        []string `json:"tags,omitempty" yaml:"tags,omitempty"`
}

// BundleDeploymentPolicy preserves portable narrowing and capacity. Scope,
// environment, rollout status, health, and placement remain host-owned.
type BundleDeploymentPolicy struct {
	Restrictions DeploymentRestrictions `json:"restrictions,omitempty" yaml:"restrictions,omitempty"`
	Capacity     DeploymentCapacity     `json:"capacity" yaml:"capacity"`
}

// BundleSkillRequirement pins the reviewed immutable Skill identity selected
// for one catalog requirement. Source identity is part of authority and must
// survive registry changes between hosts.
type BundleSkillRequirement struct {
	RequirementID string                   `json:"requirementId" yaml:"requirementId"`
	Identity      capability.SkillIdentity `json:"identity" yaml:"identity"`
}

// BundleCredentialNeed is a logical secret slot, never a credential binding.
// RequiredBy contains Skill requirement IDs or the reserved value "model".
type BundleCredentialNeed struct {
	Name       string   `json:"name" yaml:"name"`
	Kind       string   `json:"kind" yaml:"kind"`
	Optional   bool     `json:"optional,omitempty" yaml:"optional,omitempty"`
	RequiredBy []string `json:"requiredBy" yaml:"requiredBy"`
}

// BundleEndpointNeed preserves logical workflow routing intent. Destination,
// provider installation, binding, application identity, and callback ingress
// are deliberately resolved and regenerated by the target host.
type BundleEndpointNeed struct {
	ID       string                              `json:"id" yaml:"id"`
	Name     string                              `json:"name" yaml:"name"`
	Provider string                              `json:"provider" yaml:"provider"`
	Mode     capability.ConversationEndpointMode `json:"mode" yaml:"mode"`
	Adapter  capability.SkillIdentity            `json:"adapter" yaml:"adapter"`
}

type BundleExportRequest struct {
	Definition  *AgentDefinition
	Deployment  *AgentDeployment
	Metadata    BundleMetadata
	Manifest    ManifestMetadata
	Skills      []BundleSkillRequirement
	Credentials []BundleCredentialNeed
	Endpoints   []BundleEndpointNeed
}

// ExportBundle projects reviewed portable state into a deterministic artifact.
// The caller supplies host-derived requirements after stripping every binding;
// this package validates that they exactly cover the immutable definition.
func ExportBundle(request BundleExportRequest) (*Bundle, error) {
	if request.Definition == nil || request.Deployment == nil {
		return nil, errors.New("agent definition and deployment are required")
	}
	manifest, err := ExportManifest(ManifestExportRequest{
		Definition: request.Definition, DeploymentID: request.Deployment.ID, Metadata: request.Manifest,
	})
	if err != nil {
		return nil, err
	}
	metadata := request.Metadata
	if metadata.ID == "" {
		metadata.ID = manifest.Metadata.ID
	}
	if metadata.Version == "" {
		metadata.Version = manifest.Metadata.Version
	}
	if metadata.DisplayName == "" {
		metadata.DisplayName = manifest.Metadata.DisplayName
	}
	if metadata.Description == "" {
		metadata.Description = manifest.Metadata.Description
	}
	bundle := &Bundle{
		APIVersion: BundleAPIVersion, Kind: BundleKind, Metadata: metadata, Agent: manifest,
		Policy: BundleDeploymentPolicy{Restrictions: request.Deployment.Restrictions, Capacity: request.Deployment.Capacity},
		Skills: request.Skills, Credentials: request.Credentials, Endpoints: request.Endpoints,
	}
	canonicalizeBundle(bundle)
	bundle.Digest, err = bundleDigest(bundle)
	if err != nil {
		return nil, err
	}
	if err = bundle.Validate(); err != nil {
		return nil, err
	}
	return bundle, nil
}

func (b *Bundle) Validate() error {
	if b == nil || b.APIVersion != BundleAPIVersion || b.Kind != BundleKind || b.Agent == nil {
		return errors.New("agent bundle apiVersion, kind, and agent are required")
	}
	if !manifestIDPattern.MatchString(strings.TrimSpace(b.Metadata.ID)) || !versionPattern.MatchString(strings.TrimSpace(b.Metadata.Version)) || strings.TrimSpace(b.Metadata.DisplayName) == "" {
		return errors.New("agent bundle requires a valid id, version, and display name")
	}
	if b.Metadata.Version != b.Agent.Metadata.Version {
		return errors.New("agent bundle and manifest versions must match")
	}
	definition, err := CompileManifest(b.Agent, b.Agent.Metadata.ID, DefinitionProvenance{})
	if err != nil {
		return fmt.Errorf("agent bundle manifest: %w", err)
	}
	deployment := &AgentDeployment{
		ID: "portable-validation", Scope: capability.ScopeReference{Kind: "portable", ID: "validation"},
		DefinitionID: definition.ID, ActiveVersion: definition.Version, RolloutStatus: RolloutActive,
		Environment: "portable", Restrictions: b.Policy.Restrictions, Capacity: b.Policy.Capacity, Revision: 1,
	}
	if deployment.Capacity.MaxConcurrentRuns == 0 {
		deployment.Capacity.MaxConcurrentRuns = definition.Authority.MaxConcurrentRuns
	}
	if err = deployment.Validate(); err != nil {
		return fmt.Errorf("agent bundle deployment policy: %w", err)
	}
	if err = validateNarrowing(definition, deployment); err != nil {
		return fmt.Errorf("agent bundle deployment policy: %w", err)
	}

	declaredSkills := make(map[string]SkillRequirement, len(definition.SkillRequirements))
	for _, requirement := range definition.SkillRequirements {
		declaredSkills[requirement.SkillID] = requirement
	}
	resolvedSkills := make(map[string]capability.SkillIdentity, len(b.Skills))
	for _, requirement := range b.Skills {
		id := strings.TrimSpace(requirement.RequirementID)
		identity := requirement.Identity.Normalized()
		if _, ok := declaredSkills[id]; !ok || !identity.Valid() || resolvedSkills[id].Valid() {
			return errors.New("agent bundle Skills must uniquely resolve declared manifest requirements")
		}
		resolvedSkills[id] = identity
	}
	for id, requirement := range declaredSkills {
		if !requirement.Optional && !resolvedSkills[id].Valid() {
			return fmt.Errorf("agent bundle is missing required Skill %s", id)
		}
	}

	credentialNames := map[string]bool{}
	for _, need := range b.Credentials {
		name, kind := strings.TrimSpace(need.Name), strings.TrimSpace(need.Kind)
		if name == "" || kind == "" || credentialNames[name] || len(need.RequiredBy) == 0 {
			return errors.New("agent bundle credentials require unique names, kinds, and consumers")
		}
		credentialNames[name] = true
		for _, consumer := range need.RequiredBy {
			if consumer != "model" && declaredSkills[consumer].SkillID == "" {
				return fmt.Errorf("agent bundle credential %s references unknown consumer %s", name, consumer)
			}
		}
	}

	channels := make(map[string]bool, len(definition.Channels))
	for _, channel := range definition.Channels {
		channels[channel.EndpointID] = true
	}
	endpointIDs := map[string]bool{}
	for _, endpoint := range b.Endpoints {
		id := strings.TrimSpace(endpoint.ID)
		adapter := endpoint.Adapter.Normalized()
		if !channels[id] || endpointIDs[id] || strings.TrimSpace(endpoint.Name) == "" || strings.TrimSpace(endpoint.Provider) == "" || !adapter.Valid() || (endpoint.Mode != capability.ConversationEndpointChannel && endpoint.Mode != capability.ConversationEndpointDirect) {
			return errors.New("agent bundle endpoints must uniquely resolve declared channel routes")
		}
		adapterDeclared := false
		for _, identity := range resolvedSkills {
			if identity.Equal(adapter) {
				adapterDeclared = true
				break
			}
		}
		if !adapterDeclared {
			return fmt.Errorf("agent bundle endpoint %s adapter is not a resolved Agent Skill", id)
		}
		endpointIDs[id] = true
	}
	for id := range channels {
		if !endpointIDs[id] {
			return fmt.Errorf("agent bundle is missing endpoint requirement %s", id)
		}
	}
	wantDigest, err := bundleDigest(b)
	if err != nil {
		return err
	}
	if b.Digest != wantDigest {
		return errors.New("agent bundle digest does not match its portable content")
	}
	return nil
}

func EncodeBundleYAML(bundle *Bundle) ([]byte, error) {
	if err := bundle.Validate(); err != nil {
		return nil, err
	}
	jsonDocument, err := json.Marshal(bundle)
	if err != nil {
		return nil, err
	}
	var document map[string]interface{}
	if err = json.Unmarshal(jsonDocument, &document); err != nil {
		return nil, err
	}
	return yaml.Marshal(document)
}

func DecodeBundleYAML(data []byte) (*Bundle, error) {
	var document map[string]interface{}
	if err := yaml.Unmarshal(data, &document); err != nil {
		return nil, fmt.Errorf("decode agent bundle YAML: %w", err)
	}
	encoded, err := json.Marshal(document)
	if err != nil {
		return nil, err
	}
	decoder := json.NewDecoder(bytes.NewReader(encoded))
	decoder.DisallowUnknownFields()
	var bundle Bundle
	if err = decoder.Decode(&bundle); err != nil {
		return nil, fmt.Errorf("decode agent bundle contract: %w", err)
	}
	if err = bundle.Validate(); err != nil {
		return nil, err
	}
	return &bundle, nil
}

func canonicalizeBundle(bundle *Bundle) {
	if bundle == nil {
		return
	}
	sort.Strings(bundle.Metadata.Tags)
	sort.Slice(bundle.Skills, func(i, j int) bool { return bundle.Skills[i].RequirementID < bundle.Skills[j].RequirementID })
	for index := range bundle.Credentials {
		sort.Strings(bundle.Credentials[index].RequiredBy)
	}
	sort.Slice(bundle.Credentials, func(i, j int) bool { return bundle.Credentials[i].Name < bundle.Credentials[j].Name })
	sort.Slice(bundle.Endpoints, func(i, j int) bool { return bundle.Endpoints[i].ID < bundle.Endpoints[j].ID })
}

func bundleDigest(bundle *Bundle) (string, error) {
	if bundle == nil {
		return "", errors.New("agent bundle is required")
	}
	copy := *bundle
	copy.Digest = ""
	encoded, err := json.Marshal(copy)
	if err != nil {
		return "", fmt.Errorf("encode agent bundle digest: %w", err)
	}
	digest := sha256.Sum256(encoded)
	return "sha256:" + hex.EncodeToString(digest[:]), nil
}
